### ISSUE TITLE
Debian base image?

### ISSUE THREAD

**Issue by TJM** [puppetlabs/puppet-dev-tools#12]
I realize that the change from Alpine to CentOS was based on the ability to use a "package" based PDK (which is a good thing), however, that resulted in over 1.1GB more size. I prefer Centos to Debian most of the time, since that what I use for *all* my customer environments, but even I have to admit that starting from `debian:stretch-slim` at ~55MB seems better than `centos:7` at ~202MB. I have a branch where I am experimenting with this already, but I am also trying to combine that with not installing a *fourth* ruby. See #7 

I don't suppose we could convince "the powers that be" to release an Alpine Linux package?

(shrug)

Tommy

**Comment by ccaum** [comment]
Sorry for never replying to this. We ended up rebuilding the image on debian slim-buster but it didn't really have a big effect unfortunately.

**Comment by TJM** [comment]
Thanks! Keep beating on "the powers that be" to release an APK package for PDK, please!?
